Changing api
asko328P/reduxlearningproject pull request #5
Opened 2022-07-15 14:34 UTC by asko328P

Changed api, updated registration forms, still have to implement meaningful redirection

2022-07-15 15:02 UTC, nikolamajmunovic requested changes
remove forgot password
error handling 
set phone number in form
validate email
validate password(some regex for example min 8 char with numbers and one capital letter)

2022-07-15 15:04 UTC, nikolamajmunovic commented on src/actions/auth.js
> +        console.log('There is already an account registered with this email');
remove console.logs

2022-07-17 22:01 UTC, asko328P commented on src/services/auth.service.js
> +      phone_number: '+46934394409422754',
Inserted

2022-07-17 22:02 UTC, asko328P commented on src/actions/auth.js
> +      if (response.success === true) {
Added checks, for both register and login

2022-07-17 22:03 UTC, asko328P commented on src/actions/auth.js
> +        console.log('There is already an account registered with this email');
All console.logs removed.

2022-07-17 22:05 UTC, asko328P commented
Adjusted code, will push changes to branch tomorrow morning.

2022-07-18 13:29 UTC, merged